services:
  postgres:
    image: postgres:latest
    container_name: postgres_test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 89631139
      POSTGRES_DB: gamelist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
